version: 'sdl-vcltl.2.0.9.{build}'

os: Visual Studio 2017

platform:
    - x64

environment:
  vcltl: C:/projects/vc-ltl/
  sdl: C:/projects/sdl-vcltl/
  vcltl-url: https://github.com/Chuyu-Team/VC-LTL/releases/download/4.0.1.9/VC-LTL-4.0.1.9-Preview-Binary-VS2017.7z

skip_tags: true

init:
    - cmake --version
  
install:
    - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
    #- ps: Write-Host $env:TIME_STRING
    #- touch 1.txt
    #- 7z a %TIME_STRING%.7z ./1.txt
    #- exit 1
    
    # download vcltl and sdl:
    - appveyor DownloadFile https://github.com/SDL-mirror/SDL/archive/master.zip
    - 7z x ./master.zip -y -o./ && mv ./SDL-master/* %sdl%
    - rm -f ./master.zip
    
    # 
    - mkdir "%vcltl%"
    - appveyor DownloadFile %vcltl-url%
    - 7z x ./*.7z -y -o%vcltl%
    - rm -f ./*.7z

before_build:
    # test sdl and vcltl path
    - test -e %sdl%CMakeLists.txt && echo exist || echo %sdl%CMakeLists.txt Not exist && exit 1
    - test -e %vcltl%VC-LTL" helper for cmake.cmake" && echo exist || echo %vcltl%VC-LTL helper for cmake.cmake Not exist && exit 1
    
    # install vcltl
    - C:/projects/vc-ltl/Install.cmd /I
    
    # import vcltl.cmake and set cmake projects /MT
    - cp %vcltl%"VC-LTL helper for cmake".cmake %sdl%
    - echo include("VC-LTL helper for cmake.cmake") >> %sdl%CMakeLists.txt
    - echo set(CMAKE_C_FLAGS_RELEASE "/MT") >> %sdl%CMakeLists.txt
    
    # check file
    - tail -n 2 %sdl%CMakeLists.txt    
    
build_script:
    - cmake -G"Visual Studio 15 2017 Win64" %sdl%CMakeLists.txt -H. -Bbuild -DCMAKE_BUILD_TYPE=Release 
    - cmake --build build --config Release

after_build:
    # remove unnecessary files
    - rm -f %sdl%build/Release/*.exp
    - rm -f %sdl%build/Release/*.pdb
    - rm -f %sdl%build/Release/SDL2-static.lib
    
    # copy include and source code files
    - cp -r %sdl%include %sdl%build/Release/
    - cp -r %sdl%src %sdl%build/Release/
    #- cd %sdl%
    #- set LatestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
    
    - 7z a sdl-vcltl-%TIME_STRING%.7z %sdl%build/Release/*
    - appveyor PushArtifact sdl-vcltl-%TIME_STRING%.7z
    
#artifacts:
    #- path: build/Release
    #artifacts path name must be appveyor API
  
deploy:
    - provider: GitHub
      description: 'weekly build sdl-vcltl' 
      auth_token:
        secure: b7z/bl9MpzzCY+CYah15JF9aJbut5gtIWcpiZOoZpVc41W7NmKOOeB40RO7HiiK/
      draft: false
      tag: SDL%TIME_STRING%
      on:  
        APPVEYOR_REPO_TAG: false
