version: 'sdl-vcltl.0.0.{build}'

os: Visual Studio 2017

platform:
    - x64

environment:
  vcltl: C:/projects/vc-ltl/
  sdl: C:/projects/sdl-vcltl/
  
init:
    - cmake --version
  
install:
    # download vcltl and sdl:
    - appveyor DownloadFile https://github.com/SDL-mirror/SDL/archive/master.zip
    - 7z x ./master.zip -y -o./ && mv ./SDL-master/* %sdl%
    - rm -f ./master.zip
    - appveyor DownloadFile https://github.com/Chuyu-Team/VC-LTL/archive/master.zip
    - 7z x ./master.zip -y -o./ && mv./VC-LTL-master/* %vcltl%
    - rm -f ./master.zip

before_build:
    # test sdl and vcltl path
    - test -e %sdl%CMakeLists.txt && echo "exist" || echo %sdl%CMakeLists.txt Not exist && exit 1
    - test -e %vcltl%VC-LTL" helper for cmake.cmake" && echo exist || echo %vcltl%VC-LTL helper for cmake.cmake Not exist && exit 1
    # install vcltl
    - C:/projects/vc-ltl/Install.cmd /I
    # import vcltl.cmake and set cmake projects /MT
    - cp %vcltl%"VC-LTL helper for cmake".cmake %sdl%
    - echo include("VC-LTL helper for cmake.cmake") >> %sdl%CMakeLists.txt
    - echo set(CMAKE_C_FLAGS_RELEASE "/MT") >> %sdl%CMakeLists.txt
    # check file
    - tail -n 2 %sdl%CMakeLists.txt    
    
build_script:
    - cmake -G"Visual Studio 15 2017 Win64" %sdl%CMakeLists.txt -H. -Bbuild -DCMAKE_BUILD_TYPE=Release 
    - cmake --build build --config Release

after_build:
    # copy include files
    - cp -r %sdl%include %sdl%build/Release/
    - cp -r %sdl%src %sdl%build/Release/
    #- cd %sdl%
    #- set LatestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
    #- 7z a %LatestTag%.zip ../build/Release/*
    #- appveyor PushArtifact %LatestTag%.zip
    
artifacts:
    - path: build/Release
    #artifacts path name must be appveyor API
  
deploy:
    - provider: GitHub
      auth_token:
        secure: b7z/bl9MpzzCY+CYah15JF9aJbut5gtIWcpiZOoZpVc41W7NmKOOeB40RO7HiiK/
      draft: false
      on:  
        APPVEYOR_REPO_TAG: true
